name: jupiter_aggregator
description: Jupiter aggregator api client
version: 1.0.0
homepage: https://jup.ag

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  json_annotation: ^4.0.1

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^5.0.0
